version: "3"

services:
    jenkins:
        image: jsonsilva/jenkins
        build: 
            context: ./
            dockerfile: .
        ports: 
            - "8080:8080"
            - "50000:50000"
        networks: 
            - sonarnet
        container_name: jenkins_dev
        volumes: 
            - volume_jenkins:/var/jenkins_home
    
    sonarqube:
        image: sonarqube:community
        depends_on:
            - db
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonar
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
        ports:
            - "9000:9000"
        networks: 
        - sonarnet
    db:
        image: postgres
        environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data
        networks: 
            - sonarnet

volumes:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    postgresql:
    postgresql_data:
    volume_jenkins:
        driver: local

networks: 
    sonarnet: