version: "3"

services:
    jenkins:
        image: jsonsilva/jenkins
        build: 
            context: ./
            dockerfile: .
        ports: 
            - "8080:8080"
            - "50000:50000"
        networks: 
            - sonarnet
        container_name: jenkins_dev
        volumes: 
            - volume_jenkins:/var/jenkins_home

volumes:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    postgresql:
    postgresql_data:
    volume_jenkins:
        driver: local

networks: 
    sonarnet: