pipeline{
    agent{
        label "node"
    }
    stages{
        stage("Compilando aplicação"){
            steps{
                bat 'dotnet build ./todobackend.sln'
            }
        }
    }
}